[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]
aptPkgs = []

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:8000 -t public"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"
