[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pgsql', 'php82Extensions.pdo']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php artisan storage:link', 'php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache']

[start]
cmd = 'php artisan migrate --force && php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=$PORT --max-requests=250'
